export const STARTED_LOADING_DATUM_DETAILS = 'STARTED_LOADING_DATUM_DETAILS';
export const FINISHED_LOADING_DATUM_DETAILS  = 'FINISHED_LOADING_DATUM_DETAILS ';
export const ERROR_LOADING_DATUM_DETAILS  = 'ERROR_LOADING_DATUM_DETAILS ';